---
engine: knitr
title: Club Meetings
---

# Welcome

- Welcome to the Pharmaverse Examples book club! 
- "book": [Pharmaverse Examples](https://pharmaverse.github.io/examples/)
- These slides are available at [dslc.io/pharmaverse](https://dslc.io/pharmaverse).
- We follow the [Data Science Learning Community Code of Conduct](https://dslc.io/code_of_conduct.html).

::: notes
- You can add notes on each slide with blocks like this!
- Load a deck in the browser and type "s" to see these notes.
:::

## Book club meetings

-   Volunteer leads discussion of a set of examples
    -   **This is the best way to learn the material.**
-   Presentations: 
    -   Review of material
    -   Questions you have
    -   Maybe live demo
-   More info about editing: [this github repo](https://github.com/r4ds/bookclub-pharmaverse).
-   Recorded, available on the [Data Science Learning Community YouTube Channel (DSLC.video)](http://dslc.video).

## Pace

-   **Goal:** TBD/week
-   Ok to split overwhelming example sets
-   Ok to combine short example sets
-   Meet ***every*** week except holidays, etc
    -   Ideally can discuss even if presenter unavailable

## Learning objectives (LOs)

-   Students who study with LOs in mind ***retain more.***
-   **Tips:**
    -   Think "After today's session, you will be able to {LO}".
    -   *Very* roughly **1 per heading.**
